# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-30 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.CharField(max_length=200)),
                ('double_avg_crossed', models.BooleanField(default=False)),
            ],
        ),
    ]
