# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-30 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareView', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='share_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
