# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareView', '0002_share_share_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='share_5day_max_agr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='share',
            name='share_buy_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='share',
            name='share_buy_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='share',
            name='share_sell_price',
            field=models.FloatField(default=0.0),
        ),
    ]
