# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-12 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareView', '0003_auto_20170131_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='share_sell_price',
            new_name='share_stop_price',
        ),
    ]
