# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-12 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareView', '0004_auto_20170212_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='share_7day_mwa_agr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='share',
            name='supervision_status',
            field=models.BooleanField(default=False),
        ),
    ]
