# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-12 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareView', '0005_auto_20170212_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='share_code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
