# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-21 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareView', '0006_auto_20170212_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='max_risk',
            field=models.FloatField(default=0.0),
        ),
    ]
